# Makefile with specific designed tasks

all: program1 program2 program3

program1: program1.js
					node program1.js

program2: program2.js
					node program2.js

program3: program3.js
					node program3.js